//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cecom.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cecom.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_entel {
            get {
                object obj = ResourceManager.GetObject("logo_entel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Reporte de Eventos&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            margin: 20px;
        ///            background-color: #f4f4f4;
        ///        }
        ///
        ///        h1 {
        ///            text-align: center;
        ///            color: #333;
        ///        }
        ///
        ///        table {
        ///            width: 100%;
        ///            border-collapse: collapse;
        ///            margin-top: 20px;
        ///            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        ///        }
        ///
        ///        [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string reporte_eventosM {
            get {
                return ResourceManager.GetString("reporte_eventosM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        table {
        ///            border-collapse: collapse;
        ///            width: 100%;
        ///        }
        ///
        ///        th, td {
        ///            border: 1px solid black;
        ///            padding: 8px;
        ///            text-align: left;
        ///        }
        ///
        ///        th {
        ///            background-color: #f2f2f2;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Reporte de Usuarios&lt;/h1&gt;
        ///    &lt;table border=&quot;1&quot;&gt;
        ///        &lt;thead&gt;
        ///            &lt;tr&gt;
        ///                &lt;th&gt;Usuario&lt;/th&gt;
        ///                &lt;th&gt;Correo Electronico&lt;/th&gt;
        ///                &lt;t [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string reporte_usuarios {
            get {
                return ResourceManager.GetString("reporte_usuarios", resourceCulture);
            }
        }
    }
}
